# When new parameters or such are introduced, ORStools/__init.py will need to be adapted.
providers:
- ENV_VARS:
    ORS_QUOTA: X-Ratelimit-Limit
    ORS_REMAINING: X-Ratelimit-Remaining
  base_url: https://api.openrouteservice.org
  key: ''
  name: openrouteservice
  timeout: 60
